name: 'Setup NATS'
description: 'Setup a NATS instance'
author: 'Lbrictson'
branding:
  icon: 'database'
  color: 'blue'
inputs:
  # See https://hub.docker.com/_/nats for supported versions
  nats_version:
    description: 'Version of NATS to use'
    required: false
    default: '1.3.0'
runs:
  using: 'docker'
  image: 'Dockerfile'